### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by AbashkinAlex**

### CODE REVIEW

**Comment by Dmytriy-Litvinenko** [comment]
Cаня, привет! У нас в компании набор джавистов идёт. Не хочешь на собес
сходить? Если без опыта 250 старт, каждые 3 месяца ап в 100-200 в
зависимости от результатов.

2016-09-12 14:13 GMT+03:00 Aleks-Abashkin <notifications@github.com>:

**Comment by AbashkinAlex** [comment]
Хай)  я думаю что предложение интересное, но у меня уже есть предложение по
моей основной специальности и по перспективам оно даже лучше твоего. Если
что-то не сростется у меня, конечно обращусь к тебе. Спасибо, что не
забываете)

 Как ты? Ты уже мидл?  Что у тебя с за сейчас?

25 нояб. 2017 г. 10:25 AM пользователь "Dmitriy Litvinenko" <
notifications@github.com> написал:

Cаня, привет! У нас в компании набор джавистов идёт. Не хочешь на собес
сходить? Если без опыта 250 старт, каждые 3 месяца ап в 100-200 в
зависимости от результатов.

2016-09-12 14:13 GMT+03:00 Aleks-Abashkin <notifications@github.com>:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
> https://github.com/AbashkinAlex/WebApp/pull/12
> Commit Summary
>
> - For branch "dev"
> - initial commit
> - Message nullable - true
> - pictures are uploaded and saved on AWS S3
> - Better AccessDenied page.
> - picture paths are saved to db, but mapping with user is absent. aws
> credentials are moved to application.properties from the controller
> - aws credentials are moved to application.properties. pictures are
> saved to db, but mapping with user is absent.
> - gallery with alien thumbnails
> - thumbnails+
> - finish commit for registration
> - Merge pull request #5 from AbashkinAlex/master
> - Merge pull request #8 from AbashkinAlex/feature/2-create-
> gallery-with-multyuploading-pictures
> - initial commit
> - Merge pull request #10 from AbashkinAlex/feature/3-gallery
> - Merge remote-tracking branch 'remotes/origin/dev' into
> feature/1-create-dashboards
> - Merge remote-tracking branch 'remotes/origin/dev' into
> feature/1-create-dashboards
> - Merge pull request #11 from AbashkinAlex/feature/1-create-dashboards
>
> File Changes
>
> - *M* .gitignore
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-0> (1)
> - *M* pom.xml
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-1> (29)
> - *M* src/main/java/com/webapp/configuration/
> HelloWorldConfiguration.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-2> (35)
> - *M* src/main/java/com/webapp/configuration/SecurityConfiguration.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-3> (31)
> - *M* src/main/java/com/webapp/configuration/
> SecurityWebApplicationInitializer.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-4> (8)
> - *M* src/main/java/com/webapp/controller/AdminDashController.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-5> (116)
> - *A* src/main/java/com/webapp/controller/GalleryController.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-6> (2)
> - *M* src/main/java/com/webapp/controller/HelloWorldController.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-7> (99)
> - *M* src/main/java/com/webapp/dao/AbstractDao.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-8> (2)
> - *A* src/main/java/com/webapp/dao/PictureDao.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-9> (22)
> - *A* src/main/java/com/webapp/dao/PictureDaoImpl.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-10> (28)
> - *M* src/main/java/com/webapp/dao/UserDao.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-11> (2)
> - *M* src/main/java/com/webapp/dao/UserDaoImpl.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-12> (4)
> - *A* src/main/java/com/webapp/model/Picture.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-13> (45)
> - *M* src/main/java/com/webapp/model/User.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-14> (15)
> - *A* src/main/java/com/webapp/service/PictureService.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-15> (20)
> - *A* src/main/java/com/webapp/service/PictureServiceImpl.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-16> (40)
> - *M* src/main/java/com/webapp/service/UserService.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-17> (3)
> - *M* src/main/java/com/webapp/service/UserServiceImpl.java
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-18> (6)
> - *M* src/main/webapp/WEB-INF/views/accessDenied.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-19> (10)
> - *D* src/main/webapp/WEB-INF/views/dashboards/admin/cities/
> cityEdit.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-20> (211)
> - *D* src/main/webapp/WEB-INF/views/dashboards/admin/cities/
> cityTable.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-21> (204)
> - *D* src/main/webapp/WEB-INF/views/dashboards/admin/countries/
> countryEdit.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-22> (195)
> - *D* src/main/webapp/WEB-INF/views/dashboards/admin/countries/
> countryTable.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-23> (200)
> - *D* src/main/webapp/WEB-INF/views/dashboards/admin/streets/
> streetEdit.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-24> (216)
> - *D* src/main/webapp/WEB-INF/views/dashboards/admin/streets/
> streetTable.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-25> (200)
> - *A* src/main/webapp/WEB-INF/views/dashboards/admin/userBoard(with
> modal window).jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-26> (43)
> - *M* src/main/webapp/WEB-INF/views/dashboards/admin/userBoard.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-27> (49)
> - *D* src/main/webapp/WEB-INF/views/dashboards/admin/users/
> registration.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-28> (115)
> - *D* src/main/webapp/WEB-INF/views/dashboards/admin/users/
> userTable.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-29> (348)
> - *D* src/main/webapp/WEB-INF/views/dashboards/template/footer.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-30> (21)
> - *D* src/main/webapp/WEB-INF/views/dashboards/template/header.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-31> (34)
> - *D* src/main/webapp/WEB-INF/views/dashboards/user/table.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-32> (343)
> - *D* src/main/webapp/WEB-INF/views/dashboards/user/user.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-33> (457)
> - *M* src/main/webapp/WEB-INF/views/login.jsp
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-34> (15)
> - *A* src/main/webapp/resources/assets/css/reveal.css
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-35> (65)
> - *A* src/main/webapp/resources/assets/js/additional-methods.js
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-36> (617)
> - *A* src/main/webapp/resources/assets/js/dojo.reveal.js
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-37> (233)
> - *A* src/main/webapp/resources/assets/js/jquery-1.4.4.min.js
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-38> (167)
> - *A* src/main/webapp/resources/assets/js/jquery.reveal.js
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-39> (126)
> - *M* src/main/webapp/resources/dashboards/assets/css/font-
> awesome.min.css
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-40> (1964)
> - *A* src/main/webapp/resources/dashboards/assets/css/style-modal.css
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-41> (159)
> - *D* src/main/webapp/resources/dashboards/assets/img/default-
> avatar.png
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-42> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/face-0.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-43> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/face-1.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-44> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/face-2.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-45> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/face-3.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-46> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/face-4.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-47> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/face-5.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-48> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/face-6.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-49> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/face-7.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-50> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/faces/
> tim_vector.jpe
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-51> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/new_logo.png
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-52> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/sidebar-1.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-53> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/sidebar-2.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-54> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/sidebar-3.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-55> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/sidebar-4.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-56> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/sidebar-5.jpg
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-57> (0)
> - *D* src/main/webapp/resources/dashboards/assets/img/tim_80x80.png
> <https://github.com/AbashkinAlex/WebApp/pull/12/files#diff-58> (0)
>
> Patch Links:
>
> - https://github.com/AbashkinAlex/WebApp/pull/12.patch
> - https://github.com/AbashkinAlex/WebApp/pull/12.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AbashkinAlex/WebApp/pull/12>, or mute the thread
> <https://github.com/notifications/unsubscribe-
auth/AQ3jCFU2rdBUnRPwmH2RCgzO-cfz6UNoks5qpTPrgaJpZM4J6eZA>
> .
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/AbashkinAlex/WebApp/pull/12#issuecomment-346926503>,
or mute
the thread

**Comment by AbashkinAlex** [comment]
Какая ЗП сейчас у тебя?

25 нояб. 2017 г. 2:48 PM пользователь "Александр Абашкин" <
abashkin.alex.serg@gmail.com> написал:

**Comment by Dmytriy-Litvinenko** [comment]
У нас нет такой градации. Сейчас у  меня 500+ бонусы. Занимаюсь Хайбрис,
загрузка по уши.

25 ноября 2017 г., 14:48 пользователь Aleks-Abashkin <
notifications@github.com> написал:

**Pull request merged**
